services:
  script-manager:
    build:
      context: https://github.com/fruitcake514/script-manager.git
    container_name: script-manager
    environment:
      - PUID=xxx
      - PGID=xxx
    ports:
      - "9050:8080"
      - "9051-9075:9051-9075"
    volumes:
      - ./script-manager/scripts:/scripts
    restart: unless-stopped
