services:
  script-manager:
    build:
      context: .
    container_name: script-manager
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - "9050:8080"
      - "9051-9075:9051-9075"
    volumes:
      - ./script-manager/scripts:/scripts
      - ./script-manager/data:/data
    restart: unless-stopped
